export const SUBJECTS = {
  francais: {
    id: 'francais',
    label: 'Français',
    dir: 'ltr',
    lang: 'fr',
    fontBody: 'font-serif',
    sections: {
      contextualisation: { label: 'Contextualisation', icon: 'ClipboardList' },
      comprehension:     { label: 'Compréhension',     icon: 'Search' },
      langue:            { label: 'Langue',             icon: 'PenTool' },
      reaction:          { label: 'Réaction',           icon: 'MessageCircle' },
    },
    ui: {
      examLabel: 'Examen Régional',
      subtitle: 'Examen Régional · Français · 1ère Bac',
      questionLabel: 'Question',
      questionsLabel: 'questions',
      textLabel: 'Texte',
      productionLabel: 'Production écrite',
      nextLabel: 'Suivant',
      prevLabel: 'Précédent',
      quitLabel: 'Quitter',
      homeLabel: 'Accueil',
      retryLabel: 'Recommencer',
      trueLabel: 'Vrai',
      falseLabel: 'Faux',
      yourAnswerLabel: 'Votre réponse :',
      expectedLabel: 'Réponse attendue :',
      notAnsweredLabel: 'Non répondu',
      copyLabel: 'Copier pour IA',
      copiedLabel: 'Copié !',
      correctionLabel: 'Correction',
      seeCorrection: 'Voir la correction',
      aiCorrectionTag: 'Correction IA',
      modelAnswerLabel: 'Réponse modèle',
      yourChoiceLabel: 'Votre choix',
      placeholder: 'Tapez votre réponse...',
      writePlaceholder: 'Rédigez votre texte argumentatif ici... (~15 lignes)',
      wordLabel: 'mot',
      wordsLabel: 'mots',
      filterAll: 'Tous',
      finishedLabel: 'Terminés',
      examsLabel: 'Examens',
      worksLabel: 'Œuvres',
      criteriaLabel: 'Critères d\'évaluation',
      aiCopyTitle: 'Correction par IA',
      aiCopyDesc: 'Copie tes réponses et colle-les dans ChatGPT ou Claude ou Gemini pour une correction détaillée des questions ouvertes et de ta production écrite.',
      aiInstruction: 'Corrige toutes les réponses ci-dessus. Pour chaque question, indique si la réponse est correcte ou incorrecte, donne la bonne réponse le cas échéant, et attribue une note. À la fin, donne une note globale sur 20.',
    },
  },
  ijtima3iyat: {
    id: 'ijtima3iyat',
    label: 'الاجتماعيات',
    dir: 'rtl',
    lang: 'ar',
    fontBody: 'font-arabic',
    sections: {
      geography: { label: 'الجغرافيا', icon: 'Globe' },
      history:   { label: 'التاريخ',   icon: 'BookOpen' },
    },
    ui: {
      examLabel: 'الامتحان الجهوي',
      subtitle: 'الامتحان الجهوي · الاجتماعيات · الأولى باك',
      questionLabel: 'السؤال',
      questionsLabel: 'أسئلة',
      textLabel: 'الوثائق',
      productionLabel: 'إنتاج مقالي',
      nextLabel: 'التالي',
      prevLabel: 'السابق',
      quitLabel: 'خروج',
      homeLabel: 'الرئيسية',
      retryLabel: 'إعادة',
      trueLabel: 'صحيح',
      falseLabel: 'خطأ',
      yourAnswerLabel: 'إجابتك :',
      expectedLabel: 'الإجابة المتوقعة :',
      notAnsweredLabel: 'لم تتم الإجابة',
      copyLabel: 'نسخ للذكاء الاصطناعي',
      copiedLabel: 'تم النسخ !',
      correctionLabel: 'التصحيح',
      seeCorrection: 'عرض التصحيح',
      aiCorrectionTag: 'تصحيح بالذكاء الاصطناعي',
      modelAnswerLabel: 'الإجابة النموذجية',
      yourChoiceLabel: 'اختيارك',
      placeholder: 'اكتب إجابتك...',
      writePlaceholder: 'اكتب مقالتك هنا...',
      wordLabel: 'كلمة',
      wordsLabel: 'كلمات',
      filterAll: 'الكل',
      finishedLabel: 'مكتملة',
      examsLabel: 'امتحانات',
      worksLabel: 'المواضيع',
      criteriaLabel: 'معايير التقييم',
      aiCopyTitle: 'تصحيح بالذكاء الاصطناعي',
      aiCopyDesc: 'انسخ إجاباتك والصقها في ChatGPT أو Claude للحصول على تصحيح مفصل للأسئلة المفتوحة والمقال.',
      aiInstruction: 'صحح جميع الإجابات أعلاه. لكل سؤال، حدد ما إذا كانت الإجابة صحيحة أو خاطئة، وأعط الإجابة الصحيحة عند الحاجة، وامنح نقطة. في النهاية، أعط ملاحظة إجمالية على 20.',
    },
  },
  arabiya: {
    id: 'arabiya',
    label: 'اللغة العربية',
    dir: 'rtl',
    lang: 'ar',
    fontBody: 'font-arabic',
    sections: {
      nousous: { label: 'النصوص', icon: 'BookOpen' },
      lougha:  { label: 'علوم اللغة', icon: 'PenTool' },
    },
    ui: {
      examLabel: 'الامتحان الجهوي',
      subtitle: 'الامتحان الجهوي · اللغة العربية · الأولى باك',
      questionLabel: 'السؤال',
      questionsLabel: 'أسئلة',
      textLabel: 'نص الانطلاق',
      productionLabel: 'التعبير والإنشاء',
      nextLabel: 'التالي',
      prevLabel: 'السابق',
      quitLabel: 'خروج',
      homeLabel: 'الرئيسية',
      retryLabel: 'إعادة',
      trueLabel: 'صحيح',
      falseLabel: 'خطأ',
      yourAnswerLabel: 'إجابتك :',
      expectedLabel: 'الإجابة المتوقعة :',
      notAnsweredLabel: 'لم تتم الإجابة',
      copyLabel: 'نسخ للذكاء الاصطناعي',
      copiedLabel: 'تم النسخ !',
      correctionLabel: 'التصحيح',
      seeCorrection: 'عرض التصحيح',
      aiCorrectionTag: 'تصحيح بالذكاء الاصطناعي',
      modelAnswerLabel: 'الإجابة النموذجية',
      yourChoiceLabel: 'اختيارك',
      placeholder: 'اكتب إجابتك...',
      writePlaceholder: 'اكتب إنشاءك هنا...',
      wordLabel: 'كلمة',
      wordsLabel: 'كلمات',
      filterAll: 'الكل',
      finishedLabel: 'مكتملة',
      examsLabel: 'امتحانات',
      worksLabel: 'المواضيع',
      criteriaLabel: 'معايير التقييم',
      aiCopyTitle: 'تصحيح بالذكاء الاصطناعي',
      aiCopyDesc: 'انسخ إجاباتك والصقها في ChatGPT أو Claude للحصول على تصحيح مفصل.',
      aiInstruction: 'صحح جميع الإجابات أعلاه. لكل سؤال، حدد ما إذا كانت الإجابة صحيحة أو خاطئة، وأعط الإجابة الصحيحة عند الحاجة، وامنح نقطة. في النهاية، أعط ملاحظة إجمالية على 20.',
    },
  },
  islamiyat: {
    id: 'islamiyat',
    label: 'التربية الإسلامية',
    dir: 'rtl',
    lang: 'ar',
    fontBody: 'font-arabic',
    sections: {
      wadiya:  { label: 'الوضعية التقويمية', icon: 'BookOpen' },
      fiqh:    { label: 'الفقه والقيم', icon: 'Heart' },
    },
    ui: {
      examLabel: 'الامتحان الجهوي',
      subtitle: 'الامتحان الجهوي · التربية الإسلامية · الأولى باك',
      questionLabel: 'السؤال',
      questionsLabel: 'أسئلة',
      textLabel: 'السندات',
      productionLabel: 'إنتاج كتابي',
      nextLabel: 'التالي',
      prevLabel: 'السابق',
      quitLabel: 'خروج',
      homeLabel: 'الرئيسية',
      retryLabel: 'إعادة',
      trueLabel: 'صحيح',
      falseLabel: 'خطأ',
      yourAnswerLabel: 'إجابتك :',
      expectedLabel: 'الإجابة المتوقعة :',
      notAnsweredLabel: 'لم تتم الإجابة',
      copyLabel: 'نسخ للذكاء الاصطناعي',
      copiedLabel: 'تم النسخ !',
      correctionLabel: 'التصحيح',
      seeCorrection: 'عرض التصحيح',
      aiCorrectionTag: 'تصحيح بالذكاء الاصطناعي',
      modelAnswerLabel: 'الإجابة النموذجية',
      yourChoiceLabel: 'اختيارك',
      placeholder: 'اكتب إجابتك...',
      writePlaceholder: 'اكتب إجابتك هنا...',
      wordLabel: 'كلمة',
      wordsLabel: 'كلمات',
      filterAll: 'الكل',
      finishedLabel: 'مكتملة',
      examsLabel: 'امتحانات',
      worksLabel: 'المواضيع',
      criteriaLabel: 'معايير التقييم',
      aiCopyTitle: 'تصحيح بالذكاء الاصطناعي',
      aiCopyDesc: 'انسخ إجاباتك والصقها في ChatGPT أو Claude للحصول على تصحيح مفصل.',
      aiInstruction: 'صحح جميع الإجابات أعلاه. لكل سؤال، حدد ما إذا كانت الإجابة صحيحة أو خاطئة، وأعط الإجابة الصحيحة عند الحاجة، وامنح نقطة. في النهاية، أعط ملاحظة إجمالية على 20.',
    },
  },
}

export function getSubject(exam) {
  return SUBJECTS[exam?.subject] || SUBJECTS.francais
}
